# Generated by Django 5.0.6 on 2024-05-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbrd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='intensity',
            field=models.FloatField(default='1'),
        ),
    ]
